kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apim-operator
  namespace: wso2-system
subjects:
- kind: ServiceAccount
  name: apim-operator
  # Replace this with the namespace the operator is deployed in.
  namespace: wso2-system
roleRef:
  kind: ClusterRole
  name: apim-operator
  apiGroup: rbac.authorization.k8s.io
