apiVersion: wso2.com/v1alpha1
kind: RateLimiting
metadata:
  name: testing2-ratelimiting
spec:
  type: Subscription             # application ,subscription
  #description: Allow 1000 requests per minute
  timeUnit: min
  unitTime: 1
  requestCount:
   limit: 2000
  bandwidth:
   dataAmount: ""
   dataUnit: ""
  #stopOnQuotaReach: true
  # conditions:  # not required for application and subscription policies
  #   headerCondition:
  #     headerName: “host”
  #     headerValue: “abc.com”
  #   ipCondition:
  #     type: ipRange
  #     specificIp: ""
  #     negation : no
  #     startIp: 10.100.7.2
  #     endIp: 10.100.7.255